In [1]:
import numpy as np

np.random.seed(42)

#### Exercise 01

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Exercise 02

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Exercise 03

In [4]:
# Create an array of 10 elements with numbers from 1 to 10

np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

#### Exercise 04

In [5]:
# np.random.rand: Random numbers from 0 to 1

np.random.rand(10)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [6]:
# np.random.randn: Random numbers from a Normal distribution which have mean = 0 and std = 1

np.random.randn(5, 5)

array([[-0.46947439,  0.54256004, -0.46341769, -0.46572975,  0.24196227],
       [-1.91328024, -1.72491783, -0.56228753, -1.01283112,  0.31424733],
       [-0.90802408, -1.4123037 ,  1.46564877, -0.2257763 ,  0.0675282 ],
       [-1.42474819, -0.54438272,  0.11092259, -1.15099358,  0.37569802],
       [-0.60063869, -0.29169375, -0.60170661,  1.85227818, -0.01349722]])

In [7]:
# np.random.randint: Random numbers from given numbers (from included and to not included)

np.random.randint(1, 10, size = (2, 5))

array([[3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4]])

#### Exercise 05

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Exercise 06

In [9]:
matrix = np.random.rand(3, 2)
print(matrix)

min_value = np.min(matrix)
max_value = np.max(matrix)
print(f"Min value: {min_value} \nMax value: {max_value}")

# Another way: matrix.min(), matrix.max()

[[0.18485446 0.96958463]
 [0.77513282 0.93949894]
 [0.89482735 0.59789998]]
Min value: 0.18485445552552704 
Max value: 0.9695846277645586


#### Exercise 07

In [10]:
array = np.random.randint(5, 13, size = 30)
print(array)

mean_value = np.mean(array)
print(f"Mean value: {mean_value}")

# Another way: array.mean()

[12 11 12 10 11  8  5 10 12  9 12  9  6 11  9 12  6  5  8  8  8  9  5  9
 11  9  5  5 11  5]
Mean value: 8.766666666666667


#### Exercise 08

In [11]:
l = [1, 2, 3]
array = np.asarray(l)
array

# Another way: np.array(l)

array([1, 2, 3])

In [12]:
t = (1, 2, 3)
array = np.asarray(t)
array

# Another way: np.array(t)

array([1, 2, 3])

#### Exercise 09

In [13]:
np.flip(array)

# Another way: array[::-1]

array([3, 2, 1])

#### Exercise 10

In [14]:
matrix = np.random.randn(5, 12)
matrix

array([[-1.05771093, -0.676922  ,  0.61167629,  1.03099952,  0.93128012,
        -0.83921752, -0.30921238,  0.33126343,  0.97554513, -0.47917424,
        -0.18565898, -1.10633497],
       [-1.19620662,  0.81252582,  1.35624003, -0.07201012,  1.0035329 ,
         0.36163603, -0.64511975,  0.36139561,  1.53803657, -0.03582604,
         1.56464366, -2.6197451 ],
       [ 0.8219025 ,  0.08704707, -0.29900735,  0.09176078, -1.98756891,
        -0.21967189,  0.35711257,  1.47789404, -0.51827022, -0.8084936 ,
        -0.50175704,  0.91540212],
       [ 0.32875111, -0.5297602 ,  0.51326743,  0.09707755,  0.96864499,
        -0.70205309, -0.32766215, -0.39210815, -1.46351495,  0.29612028,
         0.26105527,  0.00511346],
       [-0.23458713, -1.41537074, -0.42064532, -0.34271452, -0.80227727,
        -0.16128571,  0.40405086,  1.8861859 ,  0.17457781,  0.25755039,
        -0.07444592, -1.91877122]])

In [15]:
np.reshape(matrix, (12, 5))

array([[-1.05771093, -0.676922  ,  0.61167629,  1.03099952,  0.93128012],
       [-0.83921752, -0.30921238,  0.33126343,  0.97554513, -0.47917424],
       [-0.18565898, -1.10633497, -1.19620662,  0.81252582,  1.35624003],
       [-0.07201012,  1.0035329 ,  0.36163603, -0.64511975,  0.36139561],
       [ 1.53803657, -0.03582604,  1.56464366, -2.6197451 ,  0.8219025 ],
       [ 0.08704707, -0.29900735,  0.09176078, -1.98756891, -0.21967189],
       [ 0.35711257,  1.47789404, -0.51827022, -0.8084936 , -0.50175704],
       [ 0.91540212,  0.32875111, -0.5297602 ,  0.51326743,  0.09707755],
       [ 0.96864499, -0.70205309, -0.32766215, -0.39210815, -1.46351495],
       [ 0.29612028,  0.26105527,  0.00511346, -0.23458713, -1.41537074],
       [-0.42064532, -0.34271452, -0.80227727, -0.16128571,  0.40405086],
       [ 1.8861859 ,  0.17457781,  0.25755039, -0.07444592, -1.91877122]])

#### Exercise 11

In [16]:
l = [1, 2, 0, 0, 4, 0]
array = np.array(l)
array

array([1, 2, 0, 0, 4, 0])

In [17]:
indices = np.where(array != 0)
indices

# Another way: np.nonzero(array)

(array([0, 1, 4]),)

#### Exercise 12

In [18]:
l = [0, 5, -1, 3, 15]
array = np.asarray(l)
array = array * -2

even_numbers = array[array % 2 == 0]
even_numbers

array([  0, -10,   2,  -6, -30])

#### Exercise 13

In [19]:
array = np.random.random_sample(10)
array = np.sort(array)
array

# Another way: array.sort()

array([0.03688695, 0.05147875, 0.14489487, 0.23956189, 0.27864646,
       0.28484049, 0.48945276, 0.50267902, 0.60956433, 0.90826589])

#### Exercise 14

In [20]:
array1 = np.random.randint(0, 10, 8)
array2 = np.random.randint(0, 10, 8)
print(f"Array 1: {array1} \nArray 2: {array2}")

# Sum
arr_sum = array1 + array2

# Subtraction
arr_sub = array1 - array2

# Product
arr_prod = array1 * array2

print(f"Sum: {arr_sum} \nSubtraction: {arr_sub} \nProduct: {arr_prod}")

Array 1: [5 6 3 6 7 0 5 7] 
Array 2: [4 3 1 5 5 0 8 5]
Sum: [ 9  9  4 11 12  0 13 12] 
Subtraction: [ 1  3  2  1  2  0 -3  2] 
Product: [20 18  3 30 35  0 40 35]


#### Exercise 15

In [21]:
l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
array = np.array(l)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
np.reshape(array, (4, 3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])